version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 070211
      MYSQL_DATABASE: anything
      MYSQL_USER: root
      MYSQL_PASSWORD: 070211
    ports:
      - "3306:3306"

  spring-boot-app:
    image: gradle-wrapper:latest
    container_name: spring-boot-container
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/anything
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 070211